FROM gcc:13

# Install static analysis tool: cppcheck
RUN apt-get update && \
    apt-get install -y cppcheck && \
    apt-get clean

WORKDIR /app
COPY code_runner.sh /app/code_runner.sh
RUN chmod +x /app/code_runner.sh

ENTRYPOINT ["/app/code_runner.sh"]
