FROM golang:1.22

# Install static analysis tools: golint and go vet
RUN go install golang.org/x/lint/golint@latest

WORKDIR /app
COPY code_runner.sh /app/code_runner.sh
RUN chmod +x /app/code_runner.sh

ENTRYPOINT ["/app/code_runner.sh"]
