FROM node:20

# Install ESLint for static analysis
RUN npm install -g eslint

WORKDIR /app
COPY code_runner.sh /app/code_runner.sh
RUN chmod +x /app/code_runner.sh

ENTRYPOINT ["/app/code_runner.sh"]
