FROM python:3.11-slim

# Install static analysis tool: pylint
RUN pip install --no-cache-dir pylint

WORKDIR /app
COPY code_runner.sh /app/code_runner.sh
RUN chmod +x /app/code_runner.sh

ENTRYPOINT ["/app/code_runner.sh"]
